# Role spark-operator-controller-role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-controller-role
  namespace: spark
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
# RoleBinding for spark-operator-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-controller-rolebinding
  namespace: spark
subjects:
- kind: ServiceAccount
  name: spark-operator-controller
  namespace: spark
roleRef:
  kind: Role
  name: spark-operator-controller-role
  apiGroup: rbac.authorization.k8s.io