# spark-event-pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-event-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/spark/event
---
# spark-event-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-event-pvc
  namespace: spark
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi